from django.db.models import TextChoices
from django.utils.translation import gettext_lazy as _


class FormFieldChoices(TextChoices):
    ARRAY = "array", _("Array")
    BUTTON = "button", _("Button")
    CHECKBOX = "checkbox", _("Check Box")
    COUNTRY = "country_text", _("Country")
    COUNTY = "county_text", _("County")
    CURRENCY = "currency_int", _("Currency")
    DATE = "date", _("Date")
    TIME = "time", _("Time")
    TIME_RANGE = "time_range", _("Time Range")
    DATE_RANGE = "data_range", _("Date Range")
    DATE_TIME = "datetime", _("Date Time")
    DATE_TIME_RANGE = "date_time_range", _("Date Time Range")
    DROPDOWN = "dropdown_select", _("Drop Down")
    EMAIL = "email", _("Email")
    EXTERNAL_EVALUATION_ENDPOINT = "evaluation_url", _("External Evaluation Endpoint")
    EXTERNAL_VALIDATION_ENDPOINT = "validation_url", _("External Validation Endpoint")
    FILE = "file", _("File")
    FLOAT = "float", _("Float")
    HIDDEN = "hidden", _("HIDDEN")
    NESTED = "nested", _("Nested Form")
    INTEGER = "number", _("Integer")
    PASSWORD = "password", _("Password")
    PHONE_NUMBER = "phone_number_tel", _("Phone Number")
    RADIO = "radio", _("Radio")
    RESET = "reset", _("Reset")
    TEXT = "text", _("Text")
    URL = "url", _("URL")
    UUID = "uuid_text", _("UUID")
