# Generated by Django 5.0.7 on 2024-08-02 17:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('password', 'Password'), ('checkbox', 'Checkbox'), ('dropdown', 'Dropdown')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('validation', models.JSONField(blank=True, default=list)),
                ('options', models.JSONField(blank=True, default=list)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Form Field',
                'verbose_name_plural': 'Form Fields',
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': ('updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('name', models.CharField(max_length=100)),
                ('fields', models.ManyToManyField(to='dynamic_forms.formfield')),
            ],
            options={
                'verbose_name': 'Forms',
                'verbose_name_plural': 'Form',
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': ('updated_at',),
            },
        ),
    ]
