# Generated by Django 5.0.7 on 2024-08-03 09:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("email", "Email"),
                            ("password", "Password"),
                            ("checkbox", "Check Box"),
                            ("dropdown", "Drop Down"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Field",
                "verbose_name_plural": "Fields",
                "ordering": ("-updated_at", "-created_at"),
                "get_latest_by": ("updated_at",),
            },
        ),
        migrations.CreateModel(
            name="IndexCounter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("counter", models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FieldProperty",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("validation", models.JSONField(blank=True, default=list)),
                ("options", models.JSONField(blank=True, default=list)),
                ("style", models.TextField(blank=True, default="")),
                ("hidden", models.BooleanField(default=False)),
                ("index", models.IntegerField(default=0)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_field_property",
                        to="dynamic_forms.field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fields Properties",
                "verbose_name_plural": "Field Property",
                "ordering": ("index",),
                "get_latest_by": ("updated_at",),
            },
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "fields",
                    models.ManyToManyField(
                        related_name="form_field_order",
                        through="dynamic_forms.FieldProperty",
                        to="dynamic_forms.field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forms",
                "verbose_name_plural": "Form",
                "ordering": ("-updated_at", "-created_at"),
                "get_latest_by": ("updated_at",),
            },
        ),
        migrations.AddField(
            model_name="fieldproperty",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_field_property",
                to="dynamic_forms.form",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fieldproperty",
            unique_together={("field", "form", "index")},
        ),
    ]
