# Generated by Django 5.0.7 on 2024-08-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_forms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexCounter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("counter", models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
