# Generated by Django 5.0.7 on 2024-08-03 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_forms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="nested_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dynamic_forms.form",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("email", "Email"),
                    ("password", "Password"),
                    ("checkbox", "Check Box"),
                    ("dropdown", "Drop Down"),
                    ("nested", "Nested FORM"),
                    ("file", "File"),
                ],
                max_length=20,
            ),
        ),
    ]
