# Generated by Django 5.0.7 on 2024-08-04 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_forms", "0002_field_nested_form_alter_field_field_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IndexCounter",
        ),
        migrations.AlterField(
            model_name="field",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("email", "Email"),
                    ("password", "Password"),
                    ("checkbox", "Check Box"),
                    ("dropdown", "Drop Down"),
                    ("nested", "Nested Form"),
                    ("file", "File"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="nested_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nested_fields",
                to="dynamic_forms.form",
            ),
        ),
    ]
