# Generated by Django 5.0.7 on 2024-08-02 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_forms", "0002_indexcounter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formfieldsorder",
            options={
                "get_latest_by": ("updated_at",),
                "ordering": ("index",),
                "verbose_name": "Form Fields Order",
                "verbose_name_plural": "Form Fields Order",
            },
        ),
    ]
