# Generated by Django 5.0.7 on 2024-09-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_forms", "0003_delete_indexcounter_alter_field_field_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("array", "Array"),
                    ("checkbox", "Check Box"),
                    ("country", "Country"),
                    ("county", "County"),
                    ("currency", "Currency"),
                    ("date", "Date"),
                    ("date_range", "Date Range"),
                    ("date_time", "Date Time"),
                    ("date_time_range", "Date Time Range"),
                    ("dropdown", "Drop Down"),
                    ("email", "Email"),
                    ("file", "File"),
                    ("float", "Float"),
                    ("kra_pin", "KRA PIN"),
                    ("national_id", "National ID"),
                    ("nested", "Nested Form"),
                    ("number", "Number"),
                    ("password", "Password"),
                    ("phone_number", "Phone Number"),
                    ("radio", "Radio"),
                    ("text", "Text"),
                    ("url", "URL"),
                    ("uuid", "UUID"),
                ],
                max_length=20,
            ),
        ),
    ]
