# Generated by Django 5.0.7 on 2024-11-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_forms", "0004_alter_field_field_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("array", "Array"),
                    ("button", "Button"),
                    ("checkbox", "Check Box"),
                    ("country_text", "Country"),
                    ("county_text", "County"),
                    ("currency_int", "Currency"),
                    ("date", "Date"),
                    ("time", "Time"),
                    ("time_range", "Range Range"),
                    ("data_range", "Date Range"),
                    ("datetime", "Date Time"),
                    ("date_time_range", "Date Time Range"),
                    ("dropdown_select", "Drop Down"),
                    ("email", "Email"),
                    ("evaluation_url", "External Evaluation Endpoint"),
                    ("validation_url", "External Validation Endpoint"),
                    ("file", "File"),
                    ("float", "Float"),
                    ("hidden", "HIDDEN"),
                    ("nested", "Nested Form"),
                    ("number", "Integer"),
                    ("password", "Password"),
                    ("phone_number_tel", "Phone Number"),
                    ("radio", "Radio"),
                    ("reset", "Reset"),
                    ("text", "Text"),
                    ("url", "URL"),
                    ("uuid_text", "UUID"),
                ],
                max_length=20,
            ),
        ),
    ]
